### ISSUE TITLE
Forget helicopters...

### ISSUE THREAD

**Issue by jwarbington** [qlik-oss/core-chopper#34]
Could someone switch out the sprite for the chopper and make it the Qlik Branch Unicorn? I bet Tracy or Ana could you some good images of the unicorn.

**Comment by peol** [comment]
Hey Joe, thanks for bringing this to our attention. There are too few unicorns in this repository currently and we might have an idea to solve it:

We recently added a transition into space, and a chopper cannot really fly in space (although, the horizontally flying birds can explode, still), so perhaps the chopper... _transforms_ into a unicorn as it transcends the heavens?

If someone would hook us up with a, perhaps mechanical?, unicorn spritesheet we're definitely down to sprinkle some magic on that chopper.

It's all about bringing Qlik into the cloud(s) and beyond, with whatever means make sense.

**Comment by sublibra** [comment]
WON'T DO: Repository archived
