### ISSUE TITLE
Show stats on game end

### ISSUE THREAD

**Issue by carlhannes** [qlik-oss/core-chopper#37]
It would be wonderful if you could show a graph/stats when you've completed a game, especially if you can compare yourself to previous runs you've made, and maybe the 5 above and below you in the highscore list!

**Comment by peol** [comment]
Yup, definitely something we should do but haven't had time to do yet (slow-scrolling high score list + graphed run like an arcade game).

**Comment by sublibra** [comment]
WON'T DO: Repository archived
