### ISSUE TITLE
Introduce different game modes

### ISSUE THREAD

**Issue by MaxOlsson** [qlik-oss/core-chopper#8]
We (I) would like different game modes. 

I'm creating this issue to add visibility to my branch https://github.com/peol/core-chopper/tree/game-modes where I'm currently working on this.

The first step would be to be able to choose, and load, between different game modes, the second step would be to actually come up with and implement the game mode.

I think this is something we want in order to add an element of skill (as opposed to the pure endurance/stamina game mode we currently have), but this is open for discussion. Any comments, feedback, suggestions, or critique, are more than welcome.

**Comment by sublibra** [comment]
WON'T DO: Repository archived
